version: "3.7"
services:
  blenheim-server:
    image: docker.io/pynguins/blenheim-server:latest
    ports:
      - "7000:8000"
    volumes:
      - blenheim_bind:/etc/bind
      - blenheim_config:/app/server/config
    networks:
      - blenheim
    restart: always
  bind9:
    name: bind9
    ports:
      - "53:53"
      - "53:53/udp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - blenheim_bind:/etc/bind
      - bind_cache:/var/cache/bind
      - bind_lib:/var/lib/bind
      - bind_log:/var/log
    networks:
      - blenheim
    restart: always
  blenheim-client:
    image: docker.io/pynguins/blenheim-client:latest
    ports:
      - "1080:80"
    environment:
      BLENHEIM_SERVER_HOST: blenheim-server
    links:
      - blenheim-server
    depends_on:
      - blenheim-server
    networks:
      - blenheim
    restart: always
volumes:
  blenheim_bind:
  blenheim_config:
  bind_cache:
  bind_lib:
  bind_log:
networks:
  blenheim:
