version: "3.7"
services:
  blenheim-server:
    image: docker.io/pynguins/blenheim-server:latest
    ports:
      - 53:53
      - 7000:8000
  blenheim-client:
    image: docker.io/pynguins/blenheim-client:latest
    ports:
      - 80:80
    environment:
      BLENHEIM_SERVER_HOST: blenheim-server
    links:
      - blenheim-server
    depends_on:
      - blenheim-server
