version: "3.7"
services:
  blenheim-server:
    image: docker.io/pynguins/blenheim-server:latest
    ports:
      - "53:53"
      - "53:53/udp"
      - "7000:8000"
    volumes:
      - blenheim_bind:/etc/bind
      - blenheim_config:/app/server/config
    networks:
      - blenheim
    restart: always
  blenheim-client:
    image: docker.io/pynguins/blenheim-client:latest
    ports:
      - "1080:80"
    environment:
      BLENHEIM_SERVER_HOST: blenheim-server
    links:
      - blenheim-server
    depends_on:
      - blenheim-server
    networks:
      - blenheim
    restart: always
volumes:
  blenheim_bind:
  blenheim_config:
networks:
  blenheim:
