apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: blenheim-config
  name: blenheim-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
